name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Docker Build
        run: docker build -t enterprise-node-api .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag Docker Image
        run: docker tag enterprise-node-api ${{ secrets.DOCKERHUB_USERNAME }}/enterprise-node-api:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/enterprise-node-api:latest